// Картинки: эмблемы клубов (лежат в img/clubs) и фото игроков (грузятся с Википедии в браузере игрока).
// Эмблемы: два набора — football-logos (github.com/luukhopman/football-logos, Европа)
// и football-logos (github.com/JoseArroyave/football-logos: Бразилия, Аргентина, MLS, Саудовская лига, Япония и др.).
'use strict';

const CRESTS = {
  'АИК': 'aik.webp',
  'Аваи': 'avai.webp',
  'Айнтрахт': 'ayntraht.webp',
  'Алавес': 'alaves.webp',
  'Аль-Айн': 'al-ayn.webp',
  'Аль-Араби': 'al-arabi.webp',
  'Аль-Ахли': 'al-ahli.webp',
  'Аль-Ахли Каир': 'al-ahli-kair.webp',
  'Аль-Вакра': 'al-vakra.webp',
  'Аль-Гарафа': 'al-garafa.webp',
  'Аль-Иттифак': 'al-ittifak.webp',
  'Аль-Иттихад': 'al-ittihad.webp',
  'Аль-Кадисия': 'al-kadisiya.webp',
  'Аль-Мокаволун': 'al-mokavolun.webp',
  'Аль-Наср': 'al-nasr.webp',
  'Аль-Садд': 'al-sadd.webp',
  'Аль-Хиляль': 'al-hilyal.webp',
  'Аль-Шабаб': 'al-shabab.webp',
  'Андерлехт': 'anderleht.webp',
  'Антверпен': 'antverpen.webp',
  'Арсенал': 'arsenal.webp',
  'Архентинос Хуниорс': 'arhentinos-huniors.webp',
  'Астон Вилла': 'aston-villa.webp',
  'Аталанта': 'atalanta.webp',
  'Атлас': 'atlas.webp',
  'Атлетик Бильбао': 'atletik-bilbao.webp',
  'Атлетико': 'atletiko.webp',
  'Атлетико Минейро': 'atletiko-mineyro.webp',
  'Атлетико Паранаэнсе': 'atletiko-paranaense.webp',
  'Аустрия': 'austriya.webp',
  'Аякс': 'ayaks.webp',
  'Бавария': 'bavariya.webp',
  'Базель': 'bazel.webp',
  'Баия': 'baiya.webp',
  'Байер': 'bayer.webp',
  'Банфилд': 'banfild.webp',
  'Бари': 'bari.webp',
  'Барранкилья': 'barrankilya.webp',
  'Барселона': 'barselona.webp',
  'Бастия': 'bastiya.webp',
  'Бенфика': 'benfika.webp',
  'Бернли': 'bernli.webp',
  'Бетис': 'betis.webp',
  'Бешикташ': 'beshiktash.webp',
  'Бирмингем': 'birmingem.webp',
  'Блэкберн': 'blekbern.webp',
  'Бока Хуниорс': 'boka-huniors.webp',
  'Болонья': 'bolonya.webp',
  'Болтон': 'bolton.webp',
  'Бордо': 'bordo.webp',
  'Борнмут': 'bornmut.webp',
  'Боруссия Дортмунд': 'borussiya-dortmund.webp',
  'Боруссия Мёнхенгладбах': 'borussiya-menhengladbah.webp',
  'Ботафого': 'botafogo.webp',
  'Бохум': 'bohum.webp',
  'Брага': 'braga.webp',
  'Брайтон': 'brayton.webp',
  'Брентфорд': 'brentford.webp',
  'Брешиа': 'breshia.webp',
  'Броммапойкарна': 'brommapoykarna.webp',
  'Брондбю': 'brondbyu.webp',
  'Брюгге': 'bryugge.webp',
  'Брюне': 'bryune.webp',
  'Будё-Глимт': 'bude-glimt.webp',
  'Вади Дегла': 'vadi-degla.webp',
  'Валенсия': 'valensiya.webp',
  'Вальядолид': 'valyadolid.webp',
  'Ванкувер': 'vankuver.webp',
  'Васко да Гама': 'vasko-da-gama.webp',
  'Велес Сарсфилд': 'veles-sarsfild.webp',
  'Вердер': 'verder.webp',
  'Верона': 'verona.webp',
  'Вест Бромвич': 'vest-bromvich.webp',
  'Вест Хэм': 'vest-hem.webp',
  'Виллем II': 'villem-ii.webp',
  'Вильярреал': 'vilyarreal.webp',
  'Виссел Кобе': 'vissel-kobe.webp',
  'Витория Гимарайнш': 'vitoriya-gimaraynsh.webp',
  'Виченца': 'vichentsa.webp',
  'Вольфсбург': 'volfsburg.webp',
  'Вулверхэмптон': 'vulverhempton.webp',
  'Гавр': 'gavr.webp',
  'Галатасарай': 'galatasaray.webp',
  'Гамбург': 'gamburg.webp',
  'Ганновер': 'gannover.webp',
  'Гвадалахара': 'gvadalahara.webp',
  'Генгам': 'gengam.webp',
  'Генк': 'genk.webp',
  'Герта': 'gerta.webp',
  'Гремио': 'gremio.webp',
  'Гронинген': 'groningen.webp',
  'Гурник Забже': 'gurnik-zabzhe.webp',
  'Данди Юнайтед': 'dandi-yunayted.webp',
  'Данубио': 'danubio.webp',
  'Депортиво': 'deportivo.webp',
  'Дерби Каунти': 'derbi-kaunti.webp',
  'Дефенса и Хустисия': 'defensa-i-hustisiya.webp',
  'Дженоа': 'dzhenoa.webp',
  'Ди Си Юнайтед': 'di-si-yunayted.webp',
  'Динамо Батуми': 'dinamo-batumi.webp',
  'Динамо Загреб': 'dinamo-zagreb.webp',
  'Динамо Киев': 'dinamo-kiev.webp',
  'Динамо Москва': 'dinamo-moskva.webp',
  'Динамо Тбилиси': 'dinamo-tbilisi.webp',
  'Жирона': 'zhirona.webp',
  'Зальцбург': 'zaltsburg.webp',
  'Замалек': 'zamalek.webp',
  'Зенит': 'zenit.webp',
  'Знич Прушкув': 'znich-prushkuv.webp',
  'Зриньски': 'zrinski.webp',
  'Индепендьенте': 'independente.webp',
  'Индепендьенте дель Валье': 'independente-del-vale.webp',
  'Институто': 'instituto.webp',
  'Интер': 'inter.webp',
  'Интер Майами': 'inter-mayami.webp',
  'Интернасьонал': 'internasonal.webp',
  'Истанбул Башакшехир': 'istanbul-bashakshehir.webp',
  'Итуано': 'ituano.webp',
  'КПР': 'kpr.webp',
  'Кайзерслаутерн': 'kayzerslautern.webp',
  'Кайрат': 'kayrat.webp',
  'Кальяри': 'kalyari.webp',
  'Канн': 'kann.webp',
  'Карлсруэ': 'karlsrue.webp',
  'Квинз Парк': 'kvinz-park.webp',
  'Керетаро': 'keretaro.webp',
  'Киото Санга': 'kioto-sanga.webp',
  'Кобрелоа': 'kobreloa.webp',
  'Ковентри': 'koventri.webp',
  'Коло-Коло': 'kolo-kolo.webp',
  'Комо': 'komo.webp',
  'Копенгаген': 'kopengagen.webp',
  'Коринтианс': 'korintians.webp',
  'Краснодар': 'krasnodar.webp',
  'Кремонезе': 'kremoneze.webp',
  'Кристал Пэлас': 'kristal-pelas.webp',
  'Крузейро': 'kruzeyro.webp',
  'Кёльн': 'keln.webp',
  'Ланс': 'lans.webp',
  'Лас-Пальмас': 'las-palmas.webp',
  'Лацио': 'latsio.webp',
  'Ле-Ман': 'le-man.webp',
  'Лейтон Ориент': 'leyton-orient.webp',
  'Леон': 'leon.webp',
  'Лестер': 'lester.webp',
  'Лех': 'leh.webp',
  'Ливерпуль': 'liverpul.webp',
  'Ливорно': 'livorno.webp',
  'Лидс': 'lids.webp',
  'Лилль': 'lill.webp',
  'Лион': 'lion.webp',
  'Локомотив': 'lokomotiv.webp',
  'Локомотив Москва': 'lokomotiv-moskva.webp',
  'Лорьян': 'loryan.webp',
  'Лос-Анджелес': 'los-andzheles.webp',
  'Лос-Анджелес Гэлакси': 'los-andzheles-gelaksi.webp',
  'Майнц': 'maynts.webp',
  'Малага': 'malaga.webp',
  'Мальмё': 'malme.webp',
  'Мальорка': 'malorka.webp',
  'Манчестер Сити': 'manchester-siti.webp',
  'Манчестер Юнайтед': 'manchester-yunayted.webp',
  'Маритиму': 'maritimu.webp',
  'Марсель': 'marsel.webp',
  'Мец': 'mets.webp',
  'Мидлсбро': 'midlsbro.webp',
  'Милан': 'milan.webp',
  'Миллуолл': 'milluoll.webp',
  'Мольде': 'molde.webp',
  'Монако': 'monako.webp',
  'Монпелье': 'monpele.webp',
  'Монреаль Импакт': 'monreal-impakt.webp',
  'Монтеррей': 'monterrey.webp',
  'Нагоя Грампус': 'nagoya-grampus.webp',
  'Нанси': 'nansi.webp',
  'Нант': 'nant.webp',
  'Наполи': 'napoli.webp',
  'Насьональ': 'nasonal.webp',
  'Ницца': 'nitstsa.webp',
  'Новара': 'novara.webp',
  'Норвич': 'norvich.webp',
  'Ноттингем Форест': 'nottingem-forest.webp',
  'Нью-Йорк Космос': 'nyu-york-kosmos.webp',
  'Нью-Йорк Ред Буллз': 'nyu-york-red-bullz.webp',
  'Нью-Йорк Сити': 'nyu-york-siti.webp',
  'Ньюкасл': 'nyukasl.webp',
  'Ньюэллс Олд Бойз': 'nyuells-old-boyz.webp',
  'Нюрнберг': 'nyurnberg.webp',
  'Олимпиакос': 'olimpiakos.webp',
  'Орландо Сити': 'orlando-siti.webp',
  'Осасуна': 'osasuna.webp',
  'Осер': 'oser.webp',
  'ПСВ': 'psv.webp',
  'ПСЖ': 'pszh.webp',
  'Падова': 'padova.webp',
  'Палермо': 'palermo.webp',
  'Палмейрас': 'palmeyras.webp',
  'Панатинаикос': 'panatinaikos.webp',
  'Парма': 'parma.webp',
  'Партизан': 'partizan.webp',
  'Пасуш ди Феррейра': 'pasush-di-ferreyra.webp',
  'Пеньяроль': 'penyarol.webp',
  'Перуджа': 'perudzha.webp',
  'Пескара': 'peskara.webp',
  'Портсмут': 'portsmut.webp',
  'Порту': 'portu.webp',
  'Престон': 'preston.webp',
  'Пумас': 'pumas.webp',
  'РБ Лейпциг': 'rb-leyptsig.webp',
  'Райо Вальекано': 'rayo-valekano.webp',
  'Расинг': 'rasing.webp',
  'Реал Мадрид': 'real-madrid.webp',
  'Реал Овьедо': 'real-ovedo.webp',
  'Реал Сосьедад': 'real-sosedad.webp',
  'Рединг': 'reding.webp',
  'Реймс': 'reyms.webp',
  'Рейнджерс': 'reyndzhers.webp',
  'Ренн': 'renn.webp',
  'Ривер Плейт': 'river-pleyt.webp',
  'Рома': 'roma.webp',
  'Росарио Сентраль': 'rosario-sentral.webp',
  'Рубин': 'rubin.webp',
  'Рустави': 'rustavi.webp',
  'Саган Тосу': 'sagan-tosu.webp',
  'Салернитана': 'salernitana.webp',
  'Сампдория': 'sampdoriya.webp',
  'Сан-Паулу': 'san-paulu.webp',
  'Сандерленд': 'sanderlend.webp',
  'Санкт-Паули': 'sankt-pauli.webp',
  'Сантос': 'santos.webp',
  'Санфречче': 'sanfrechche.webp',
  'Сарагоса': 'saragosa.webp',
  'Сассуоло': 'sassuolo.webp',
  'Саутгемптон': 'sautgempton.webp',
  'Севилья': 'sevilya.webp',
  'Селтик': 'seltik.webp',
  'Сельта': 'selta.webp',
  'Сент-Этьен': 'sent-eten.webp',
  'Сересо Осака': 'sereso-osaka.webp',
  'Сидней': 'sidney.webp',
  'Синт-Трёйден': 'sint-treyden.webp',
  'Сошо': 'sosho.webp',
  'Спарта Прага': 'sparta-praga.webp',
  'Спартак': 'spartak.webp',
  'Спортинг': 'sporting.webp',
  'Спортинг Хихон': 'sporting-hihon.webp',
  'Стандард': 'standard.webp',
  'Сток Сити': 'stok-siti.webp',
  'Стрёмсгодсет': 'stremsgodset.webp',
  'Суонси': 'suonsi.webp',
  'Сьон': 'son.webp',
  'Твенте': 'tvente.webp',
  'Торино': 'torino.webp',
  'Торонто': 'toronto.webp',
  'Тоттенхэм': 'tottenhem.webp',
  'Трабзонспор': 'trabzonspor.webp',
  'Труа': 'trua.webp',
  'Тулуза': 'tuluza.webp',
  'Удинезе': 'udineze.webp',
  'Уиган': 'uigan.webp',
  'Ульсан': 'ulsan.webp',
  'Унион Берлин': 'union-berlin.webp',
  'Уотфорд': 'uotford.webp',
  'Утрехт': 'utreht.webp',
  'Фейеноорд': 'feyenoord.webp',
  'Фенербахче': 'fenerbahche.webp',
  'Фиорентина': 'fiorentina.webp',
  'Фламенго': 'flamengo.webp',
  'Флитвуд': 'flitvud.webp',
  'Флуминенсе': 'fluminense.webp',
  'Фулхэм': 'fulhem.webp',
  'Хайдук': 'hayduk.webp',
  'Халл Сити': 'hall-siti.webp',
  'Хельсингборг': 'helsingborg.webp',
  'Херенвен': 'herenven.webp',
  'Хетафе': 'hetafe.webp',
  'Хоффенхайм': 'hoffenhaym.webp',
  'Хуниор': 'hunior.webp',
  'ЦСКА': 'tsska.webp',
  'ЦСКА София': 'tsska-sofiya.webp',
  'Црвена Звезда': 'tsrvena-zvezda.webp',
  'Челси': 'chelsi.webp',
  'Чикаго Файр': 'chikago-fayr.webp',
  'Шальке': 'shalke.webp',
  'Шанхай Порт': 'shanhay-port.webp',
  'Шанхай Шэньхуа': 'shanhay-shenhua.webp',
  'Шарлеруа': 'sharlerua.webp',
  'Шарлотт': 'sharlott.webp',
  'Шахтёр': 'shahter.webp',
  'Шеффилд Юнайтед': 'sheffild-yunayted.webp',
  'Штурм': 'shturm.webp',
  'Штутгарт': 'shtutgart.webp',
  'Эвертон': 'everton.webp',
  'Эйбар': 'eybar.webp',
  'Эксетер': 'ekseter.webp',
  'Эркулес': 'erkules.webp',
  'Эспаньол': 'espanol.webp',
  'Эстудиантес': 'estudiantes.webp',
  'Ювентус': 'yuventus.webp',
};

// Лица игроков (img/players/<id>.webp) из набора FIFA-Player-Faces (github.com/saihari/FIFA-Player-Faces).
const FACES = {
  // Легенды для «Возьмёшь этого или другого?»
  'Давид Алаба': 197445,
  'Нголо Канте': 215914,
  'Филипп Лам': 121939,
  'Эстебан Камбьяссо': 138123,
  'Фрэнк Лэмпард': 5471,
  'Бастиан Швайнштайгер': 121944,
  'Леонардо Бонуччи': 184344,
  'Жером Боатенг': 183907,
  'Эшли Коул': 34079,
  'Франк Рибери': 156616,
  'Хавьер Санетти': 1041,
  'Диего Милито': 142708,
  'Джорджо Кьеллини': 138956,
  'Бранислав Иванович': 178372,
  'Джон Терри': 13732,
  'Самир Ханданович': 162835,
  'Жулио Сезар': 48717,
  'Петр Чех': 48940,
  'Марсело': 176676,
  'Кейлор Навас': 193041,
  'Пепе': 120533,
  'Рафаэль Варан': 201535,
  'Рауль': 45661,
  'Гути': 9593,
  'Роберто Карлос': 1040,
  'Жерар Пике': 152729,
  'Дани Алвес': 146530,
  'Жорди Альба': 189332,
  'Хавьер Маскерано': 142754,
  'Хави': 10535,
  'Андрес Иньеста': 41,
  'Серхио Бускетс': 189511,
  'Иван Ракитич': 168651,
  'Самюэль Это’о': 9676,
  'Ривалдо': 4231,
  'Давид Вилья': 113422,
  'Карлес Пуйоль': 13038,
  'Давид де Хеа': 193080,
  'Неманья Видич': 140601,
  'Патрис Эвра': 52091,
  'Майкл Каррик': 21146,
  'Уэйн Руни': 54050,
  'Дида': 3712,
  'Алессандро Неста': 1088,
  'Кларенс Зеедорф': 1256,
  'Дженнаро Гаттузо': 4202,
  'Андрей Шевченко': 13128,
  'Филиппо Индзаги': 1198,
  'Пепе Рейна': 24630,
  'Даниэль Аггер': 152039,
  'Мартин Шкртел': 166706,
  'Стивен Джеррард': 13743,
  'Хаби Алонсо': 45197,
  'Джордан Хендерсон': 183711,
  'Икер Касильяс': 5479,
  'Александер Исак': 233731,
  'Александер Сёрлот': 216549,
  'Алексис Мак Аллистер': 239837,
  'Алексис Санчес': 184941,
  'Алессандро Бастони': 237383,
  'Алехандро Бальде': 263578,
  'Алиссон': 212831,
  'Альфонсо Дэвис': 234396,
  'Андреа Пирло': 7763,
  'Андреас Кристенсен': 213661,
  'Андрий Лунин': 243952,
  'Антонио Рюдигер': 205452,
  'Антуан Гризманн': 194765,
  'Анхель Ди Мария': 183898,
  'Арьен Роббен': 9014,
  'Ашраф Хакими': 235212,
  'Бен Уайт': 231936,
  'Беньямин Шешко': 260592,
  'Бернарду Силва': 218667,
  'Браим Диас': 231410,
  'Брайан Мбемо': 243014,
  'Бруну Гимарайнш': 247851,
  'Бруну Фернандеш': 212198,
  'Букайо Сака': 246669,
  'Ватару Эндо': 232487,
  'Виктор Дьёкереш': 241651,
  'Виктор Осимхен': 232293,
  'Вильям Салиба': 243715,
  'Вильян Пачо': 256196,
  'Винисиус Жуниор': 238794,
  'Вирджил ван Дейк': 203376,
  'Витинья': 255253,
  'Войцех Щенсны': 186153,
  'Габриэл Жезус': 230666,
  'Габриэл Магальяйнс': 232580,
  'Габриэл Мартинелли': 251566,
  'Гави': 264240,
  'Гарет Бэйл': 173731,
  'Гарри Кейн': 202126,
  'Гарри Магуайр': 203263,
  'Гиорги Мамардашвили': 262621,
  'Глейсон Бремер': 239580,
  'Гонсало Игуаин': 167664,
  'Гонсалу Рамуш': 256903,
  'Давид Райя': 220901,
  'Дайо Упамекано': 229558,
  'Дани Ольмо': 244260,
  'Деклан Райс': 234378,
  'Дензел Дюмфрис': 233096,
  'Джамал Мусиала': 256790,
  'Джанлуиджи Буффон': 1179,
  'Джанлуиджи Доннарумма': 230621,
  'Джек Грилиш': 206517,
  'Джереми Фримпонг': 253149,
  'Джо Гомес': 225100,
  'Джуд Беллингем': 252371,
  'Дидье Дрогба': 31432,
  'Диогу Далот': 234574,
  'Доминик Собослаи': 236772,
  'Душан Влахович': 246430,
  'Дэвид Бекхэм': 250,
  'Жоан Гарсия': 259532,
  'Жоау Педро': 252042,
  'Жоау Феликс': 242444,
  'Жоржиньо': 205498,
  'Жуан Канселу': 210514,
  'Жюль Кунде': 241486,
  'Златан Ибрагимович': 41236,
  'Ибраима Конате': 237678,
  'Илья Забарный': 258781,
  'Иньяки Уильямс': 216201,
  'Йозуа Киммих': 212622,
  'Йонатан Та': 213331,
  'Йошко Гвардиол': 251517,
  'Каземиро': 200145,
  'Кай Хаверц': 235790,
  'Кака': 138449,
  'Карим Адейеми': 251852,
  'Карим Бензема': 165153,
  'Кевин Де Брюйне': 192985,
  'Кепа Аррисабалага': 206585,
  'Кертис Джонс': 242434,
  'Килиан Мбаппе': 231747,
  'Коди Гакпо': 242516,
  'Коке': 193747,
  'Конрад Лаймер': 225375,
  'Коул Палмер': 257534,
  'Кристиан Пулишич': 227796,
  'Криштиану Роналду': 20801,
  'Лаутаро Мартинес': 231478,
  'Леви Колуилл': 262859,
  'Леон Горецка': 209658,
  'Лерой Сане': 222492,
  'Лионель Месси': 158023,
  'Луис Диас': 241084,
  'Луис Суарес': 176580,
  'Луиш Фигу': 5589,
  'Лука Модрич': 177003,
  'Люка Шевалье': 251752,
  'Люка Эрнандес': 220814,
  'Майкл Олисе': 247827,
  'Мануэль Локателли': 222077,
  'Мануэль Нойер': 167495,
  'Марк Гэи': 241159,
  'Марк Кукурелья': 239231,
  'Марк-Андре тер Штеген': 192448,
  'Маркиньос': 207865,
  'Маркюс Тюрам': 228093,
  'Мартин Субименди': 248148,
  'Мартин Эдегор': 222665,
  'Матвей Сафонов': 240225,
  'Матео Ковачич': 207410,
  'Матеус Кунья': 240243,
  'Матеус Нунес': 253124,
  'Микель Мерино': 225193,
  'Мики ван де Вен': 264453,
  'Михаил Мудрик': 246340,
  'Мойсес Кайседо': 256079,
  'Морган Роджерс': 260247,
  'Мохамед Салах': 209331,
  'Неймар': 190871,
  'Нико Уильямс': 256516,
  'Николо Барелла': 224232,
  'Нони Мадуэке': 254796,
  'Нуну Мендеш': 252145,
  'Олли Уоткинс': 221697,
  'Омар Мармуш': 256675,
  'Орельен Чуамени': 241637,
  'Патрик Шик': 234236,
  'Пауло Дибала': 211110,
  'Педри': 251854,
  'Педру Нету': 238616,
  'Поль Погба': 195864,
  'Пьеро Инкапье': 256197,
  'Райан Гравенберх': 246104,
  'Райан Шерки': 251570,
  'Расмус Хёйлунн': 259399,
  'Рафаэл Леау': 241721,
  'Рафинья': 233419,
  'Рахим Стерлинг': 202652,
  'Риккардо Калафьори': 257711,
  'Рис Джеймс': 238074,
  'Рияд Марез': 204485,
  'Роберт Левандовски': 188545,
  'Роберт Санчес': 228789,
  'Робин ван Перси': 7826,
  'Родри': 231866,
  'Родриго': 243812,
  'Ромелу Лукаку': 192505,
  'Роналдиньо': 28130,
  'Рубен Диаш': 239818,
  'Садио Мане': 208722,
  'Сандро Тонали': 241096,
  'Серж Гнабри': 206113,
  'Серхио Рамос': 155862,
  'Сеск Фабрегас': 162895,
  'Скотт Мактоминей': 237238,
  'Сон Хын Мин': 200104,
  'Станислав Лоботка': 216435,
  'Тибо Куртуа': 192119,
  'Томас Мюллер': 189596,
  'Тони Кроос': 182521,
  'Трент Александер-Арнольд': 231281,
  'Тьерри Анри': 1625,
  'Уго Экитике': 257289,
  'Усман Дембеле': 231443,
  'Уэсли Снейдер': 139869,
  'Фабиан Руис': 226271,
  'Федерико Вальверде': 239053,
  'Федерико Димарко': 226268,
  'Федерико Кьеза': 235805,
  'Ферлан Менди': 228618,
  'Ферран Торрес': 241461,
  'Фил Фоден': 237692,
  'Филиппе Коутиньо': 189242,
  'Флориан Вирц': 256630,
  'Френки де Йонг': 228702,
  'Хави Симонс': 245367,
  'Херонимо Рульи': 215316,
  'Христос Цолис': 256948,
  'Хулиан Альварес': 246191,
  'Эберечи Эзе': 235794,
  'Эден Азар': 183277,
  'Эдер Милитао': 240130,
  'Эдинсон Кавани': 179813,
  'Эдуардо Камавинга': 248243,
  'Эндрю Робертсон': 216267,
  'Энтони': 255475,
  'Энтони Гордон': 242964,
  'Энцо Фернандес': 247090,
  'Эрик Гарсия': 245037,
  'Эрлинг Холанд': 239085,
  'Юрриен Тимбер': 251805,
  'Ян Облак': 200389,
};

// Английские названия статей Википедии для тех, у кого имя неоднозначное или кого нет в базе игроков.
const WIKI = {
  'Родри': 'Rodri (footballer, born 1996)', 'Гави': 'Gavi (footballer)', 'Алиссон': 'Alisson Becker',
  'Витинья': 'Vitinha (footballer, born 2000)', 'Маркиньос': 'Marquinhos', 'Эндрик': 'Endrick (footballer)',
  'Жоау Педро': 'João Pedro (footballer, born 2001)', 'Сон Хын Мин': 'Son Heung-min', 'Луис Диас': 'Luis Díaz (footballer, born 1997)',
  'Фабиан Руис': 'Fabián Ruiz', 'Педри': 'Pedri', 'Коке': 'Koke', 'Неймар': 'Neymar', 'Родриго': 'Rodrygo', 'Рафинья': 'Raphinha',
  'Жоан Гарсия': 'Joan García', 'Эрик Гарсия': 'Eric García (footballer, born 2001)', 'Роберт Санчес': 'Robert Sánchez (footballer)',
  'Габриэл Магальяйнс': 'Gabriel Magalhães', 'Габриэл Жезус': 'Gabriel Jesus', 'Габриэл Мартинелли': 'Gabriel Martinelli',
  'Бруну Гимарайнш': 'Bruno Guimarães', 'Энтони': 'Antony (footballer, born 2000)',
  'Тони Кроос': 'Toni Kroos', 'Серхио Рамос': 'Sergio Ramos', 'Луис Суарес': 'Luis Suárez', 'Поль Погба': 'Paul Pogba',
  'Гарет Бэйл': 'Gareth Bale', 'Златан Ибрагимович': 'Zlatan Ibrahimović', 'Эден Азар': 'Eden Hazard', 'Анхель Ди Мария': 'Ángel Di María',
  'Ромелу Лукаку': 'Romelu Lukaku', 'Гонсало Игуаин': 'Gonzalo Higuaín', 'Сеск Фабрегас': 'Cesc Fàbregas', 'Тьерри Анри': 'Thierry Henry',
  'Дэвид Бекхэм': 'David Beckham', 'Роналдиньо': 'Ronaldinho', 'Роналдо (Феномен)': 'Ronaldo (Brazilian footballer)', 'Кака': 'Kaká',
  'Андреа Пирло': 'Andrea Pirlo', 'Джанлуиджи Буффон': 'Gianluigi Buffon', 'Дидье Дрогба': 'Didier Drogba', 'Фернандо Торрес': 'Fernando Torres',
  'Уэсли Снейдер': 'Wesley Sneijder', 'Робин ван Перси': 'Robin van Persie', 'Арьен Роббен': 'Arjen Robben', 'Эдинсон Кавани': 'Edinson Cavani',
  'Алексис Санчес': 'Alexis Sánchez', 'Рияд Марез': 'Riyad Mahrez', 'Филиппе Коутиньо': 'Philippe Coutinho', 'Леон Горецка': 'Leon Goretzka',
  'Жоржиньо': 'Jorginho (footballer, born 1991)', 'Каземиро': 'Casemiro', 'Жоау Феликс': 'João Félix', 'Джек Грилиш': 'Jack Grealish',
  'Гарри Магуайр': 'Harry Maguire', 'Кепа Аррисабалага': 'Kepa Arrizabalaga', 'Зинедин Зидан': 'Zinedine Zidane', 'Луиш Фигу': 'Luís Figo',
  'Михаил Мудрик': 'Mykhailo Mudryk', 'Рахим Стерлинг': 'Raheem Sterling', 'Мохамед Салах': 'Mohamed Salah',
};

function crestImg(club, size = 's') {
  const f = CRESTS[club];
  if (f) return `<img class="crest crest-${size}" src="img/clubs/${f}" alt="${esc(club)}" loading="lazy">`;
  const ini = club.split(/[\s-]+/).map((w) => w[0]).join('').slice(0, 3).toUpperCase();
  return `<span class="crest crest-${size} crest-none" aria-hidden="true">${esc(ini)}</span>`;
}

// Фото игрока: своё фото из img/players, а для тех, кого нет в наборе, — с Википедии (на GitHub Pages и в Telegram).
// Картинка появляется плавно, без прыжков: до загрузки виден кружок с инициалами.
const Photos = (() => {
  const KEY = 'oldjacksons.photos.v2';
  let cache = {};
  try { cache = JSON.parse(localStorage.getItem(KEY)) || {}; } catch (e) { cache = {}; }
  const save = () => { try { localStorage.setItem(KEY, JSON.stringify(cache)); } catch (e) { /* без кэша */ } };
  const pending = new Map();

  function title(name) {
    if (WIKI[name]) return WIKI[name];
    const p = PLAYERS.find((x) => x.name === name);
    return p ? p.alt.split(' ').slice(0, name.split(' ').length).join(' ') : null;
  }
  async function summary(t) {
    const r = await fetch(`https://en.wikipedia.org/api/rest_v1/page/summary/${encodeURIComponent(t.replace(/ /g, '_'))}`);
    return r.ok ? r.json() : null;
  }
  async function wiki(name) {
    if (name in cache) return cache[name];
    if (pending.has(name)) return pending.get(name);
    const job = (async () => {
      let url = null;
      try {
        const t = title(name);
        if (t) {
          const ok = (x) => x && x.type !== 'disambiguation' && /football|soccer/i.test(x.description || '');
          let s = await summary(t);
          if (!ok(s)) s = await summary(t + ' (footballer)').catch(() => null);
          if (ok(s) && s.thumbnail) url = s.thumbnail.source;
        }
        cache[name] = url;
        save();
      } catch (e) { /* сеть недоступна: остаются инициалы */ }
      pending.delete(name);
      return url;
    })();
    pending.set(name, job);
    return job;
  }

  function show(el, url) {
    const img = new Image();
    img.alt = '';
    img.decoding = 'async';
    img.src = url;
    if (img.complete && img.naturalWidth) { el.appendChild(img); el.classList.add('loaded', 'instant'); return; }
    img.onload = () => { if (el.isConnected) { el.appendChild(img); requestAnimationFrame(() => el.classList.add('loaded')); } };
  }

  function hydrate(root = document) {
    $$('[data-ph]:not(.hyd)', root).forEach(async (el) => {
      el.classList.add('hyd');
      const name = el.dataset.ph;
      if (FACES[name]) return show(el, `img/players/${FACES[name]}.webp`);
      const url = await wiki(name);
      if (url) show(el, url);
    });
  }

  // Заранее подгрузить фото, чтобы карточка появилась уже с лицом.
  function preload(name) {
    if (FACES[name]) { const i = new Image(); i.src = `img/players/${FACES[name]}.webp`; }
  }

  return { hydrate, preload };
})();

function avatar(name, size = 'm') {
  const ini = name.replace(/\(.*\)/, '').split(' ').filter(Boolean).map((w) => w[0]).slice(0, 2).join('');
  return `<span class="ava ava-${size}" data-ph="${esc(name)}"><b>${esc(ini)}</b></span>`;
}
